### ISSUE TITLE
Cannot plan a route to Kirino

### ISSUE THREAD

**Issue by CFrunks** [maxpowa/sdx-map#2]
No matter what start position I pick, nothing happens when I hit the "Route" button when trying to get to Kirino Shipyards. Other end destinations seem to work fine

**Comment by CFrunks** [comment]
Okay I managed to plan a route but just using the Kirino Turn as the start and the kirino orbital shipyards as an end point. But when I pasted the journey into the NavOS block, nothing happens.

**Comment by maxpowa** [comment]
@CFrunks can you try now? I made some changes just after you posted this that might have fixed it, and if not it should at least show an error message if it can't route.

**Comment by maxpowa** [comment]
@CFrunks thanks for reporting this, had someone else in discord also report the same with a bit more information and I was able to reproduce it. Was specifically about starting a route from a turn point.

Latest code should not have this issue, please reopen if you're still seeing this.
